final List<Map<String, dynamic>> allAppointments = [
  {
    'patientName': 'Ana Smith',
    'time': '09:00 AM',
    'date': DateTime.now(),
    'centerName': 'Downtown Medical Center',
    'status': 'Confirmed',
    'image': 'assets/images/patient.jpeg',
  },
  {
    'patientName': 'John Doe',
    'time': '10:30 AM',
    'date': DateTime.now(),
    'centerName': 'Downtown Medical Center',
    'status': 'Pending',
    'image': 'assets/images/patient.jpeg',
  },
  {
    'patientName': 'Jane Williams',
    'time': '01:00 PM',
    'date': DateTime.now(),
    'centerName': 'Uptown Clinic',
    'status': 'Confirmed',
    'image': 'assets/images/patient.jpeg',
  },
  {
    'patientName': 'Peter Jones',
    'time': '11:00 AM',
    'date': DateTime.now().add(const Duration(days: 1)),
    'centerName': 'Uptown Clinic',
    'status': 'Confirmed',
    'image': 'assets/images/patient.jpeg',
  },
  {
    'patientName': 'Mary Brown',
    'time': '02:30 PM',
    'date': DateTime.now().add(const Duration(days: 1)),
    'centerName': 'Downtown Medical Center',
    'status': 'Pending',
    'image': 'assets/images/patient.jpeg',
  },
  {
    'patientName': 'Chris Green',
    'time': '04:00 PM',
    'date': DateTime.now().add(const Duration(days: 3)),
    'centerName': 'Uptown Clinic',
    'status': 'Confirmed',
    'image': 'assets/images/patient.jpeg',
  },
];
