// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UiPSrl32TzuzrUL1McyFIeL329xAbAE',
    appId: '1:376455430584:web:b2effca92df4f33e2c8f4d',
    messagingSenderId: '376455430584',
    projectId: 'tabby-3d3c4',
    authDomain: 'tabby-3d3c4.firebaseapp.com',
    storageBucket: 'tabby-3d3c4.firebasestorage.app',
    measurementId: 'G-6KRHYJFDJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_JYgAT9athfzwV9Fj8nDEkLSFACKXDN8',
    appId: '1:376455430584:android:710ed561443de8af2c8f4d',
    messagingSenderId: '376455430584',
    projectId: 'tabby-3d3c4',
    storageBucket: 'tabby-3d3c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB1pABKHMjH8OoctFtVkyshWYNqitwqQU',
    appId: '1:376455430584:ios:357a115b686cf45f2c8f4d',
    messagingSenderId: '376455430584',
    projectId: 'tabby-3d3c4',
    storageBucket: 'tabby-3d3c4.firebasestorage.app',
    iosBundleId: 'sy.techtoc.tabiby',
  );
}
